create table if not exists public.users (
  id bigint generated by default as identity primary key,
  full_name text not null check (char_length(btrim(full_name)) between 2 and 80),
  email text not null unique check (email = lower(email)),
  password_hash text not null check (password_hash like 'scrypt$%'),
  created_at timestamptz not null default now(),
  username text check (username is null or char_length(username) <= 40),
  pronouns text check (pronouns is null or char_length(pronouns) <= 40),
  phone text check (phone is null or char_length(phone) <= 40),
  bio text check (bio is null or char_length(bio) <= 1000),
  favorite_field text check (favorite_field is null or char_length(favorite_field) <= 80),
  preferred_section text check (preferred_section is null or char_length(preferred_section) <= 80)
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null check (expires_at > created_at)
);

create index if not exists sessions_user_id_idx on public.sessions(user_id);
create index if not exists sessions_expires_at_idx on public.sessions(expires_at);
create index if not exists sessions_token_hash_expires_at_idx
  on public.sessions(token_hash, expires_at);

alter table public.users enable row level security;
alter table public.sessions enable row level security;

revoke all on table public.users from anon, authenticated;
revoke all on table public.sessions from anon, authenticated;
grant all on table public.users to service_role;
grant all on table public.sessions to service_role;
grant usage, select on all sequences in schema public to service_role;

comment on table public.users is
  'Forgotten Scientists application users. Access only through server API routes.';
comment on table public.sessions is
  'Hashed httpOnly cookie sessions for Forgotten Scientists.';
